repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/prettier/prettier
    rev: v3.9.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.9.0"]
