## .github/workflows/ai\_update.yml

```yaml
name: Auto AI Updates

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-ai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run AI Update Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet || git commit -m "chore: AI updated README"
```

---

## scripts/update\_readme.py

```python
import os
import openai

# Load API key from environment for v1 OpenAI Python client
openai.api_key = os.getenv("OPENAI_API_KEY")

# Read existing README
with open("README.md", "r", encoding="utf-8") as f:
    current = f.read()

# Prepare prompt for AI
prompt = (
    "You are a GitHub Action assistant. "
    "Please improve and structure the following README for a Grafana dashboards project:\n\n"
    + current
)

# Call OpenAI with the new chat interface
response = openai.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant for documentation."},
        {"role": "user", "content": prompt}
    ],
    temperature=0.3,
)

# Extract and write updated content
updated = response.choices[0].message.content
with open("README.md", "w", encoding="utf-8") as f:
    f.write(updated)
```

---

### Next Steps

1. **Commit & push**:

   ```powershell
   git add .github\workflows\ai_update.yml scripts\update_readme.py
   git commit -m "fix: migrate to OpenAI Python v1 interface"
   git push origin main
   ```

2. **Verify locally** (optional but recommended):

   ```powershell
   # Inside your repo root:
   pip install openai  # installs the v1+ client
   $Env:OPENAI_API_KEY = "sk-..."  # replace with your key
   python scripts/update_readme.py  # should run without errors
   ```

3. **Re-run the GitHub Action**:

   * In your repo’s **Actions** tab, select **Auto AI Updates** and click **Re-run jobs**.
   * Confirm the workflow now completes successfully and updates your README.
